### ISSUE TITLE
Issue with Parallel Parser

### ISSUE THREAD

**Issue by TorokNRoll** [SchaeferJ/Blockchain_Parser#3]
Hello Jochen!

I have been experimenting with your two scripts:

- btc-to-csv.py
- btc_parallel.py

The single threaded script works for me, no problem.

When I run the parallel script, I get an error around the locking mechanism.

In specifically: 
     _TypeError: __init__() got an unexpected keyword argument 'ignoreLocks'_

in conjunction with this call in the generate_csv function:
    blockchain = Blockchain(BLOCK_PATH, ignoreLocks=1)

Is this something you might be familiar with? (Full error text below)

Thanks!

Cheers,
Steve

--------------------------------- Error Text ------------------------------

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "btc_parallel_OC.py", line 273, in generate_csv
    blockchain = Blockchain(BLOCK_PATH, ignoreLocks=1)
TypeError: __init__() got an unexpected keyword argument 'ignoreLocks'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "btc_parallel_OC.py", line 401, in <module>
    collector = Parallel(n_jobs=-1)(delayed(generate_csv)(BLOCK_PATH, INDEX_PATH, c) for c in s)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: __init__() got an unexpected keyword argument 'ignoreLocks'

**Comment by TorokNRoll** [comment]
Hey....

got the notification in regards to the closure of this issue.....it reminded me to write back and thank you for your reply!  

I have been traveling, and it slipped my mind to reply!

In the end, I found an alternative means to speed up the parsing using your script.

On that, thanks for your work!

Cheers,
Steve
